#ifndef APP_CONFIG_H
#define APP_CONFIG_H
#include "bsp/nano.h"

#define RADAR_STATE_SAFE 0
#define RADAR_STATE_WARNING 1

#define RADAR_ALERT_DISTANCE_CM 20

#define SERVO_MIN_ANGLE 0
#define SERVO_MAX_ANGLE 180
#define SERVO_STEP_ANGLE 1
#define SERVO_STEP_DELAY_MS 15

#define BUZZER_ALERT_FREQUENCY_HZ 2000
#define BUZZER_BEEP_ON_MS 100
#define BUZZER_BEEP_OFF_MS 100

#define SERVO_PIN D9
#define ULTRASONIC_TRIG_PIN D10
#define ULTRASONIC_ECHO_PIN D11
#define BUZZER_PIN D3
#define RED_LED1_PIN D7
#define RED_LED2_PIN D4
#define GREEN_LED1_PIN D5
#define GREEN_LED2_PIN D6

#endif

